#!/bin/bash

# Trigger this script using ./vhost sitename domain, ie. "./vhost myblog myblog.com"

# This script helps set up the following:
# * A directory under webroot, containing a docroot directory for docroot and tmp.
# * Create an Apache Vhost, using mod macro.
# * Create an empty MySQL database using the supplied db authentication.
# Based on https://github.com/tallsam/utilities/tree/master/vhost


if [ $# -lt 4 ]; then
  echo "Usage: $0 sitename domain aliases mysql_root_pass"
  exit;
fi;

if [ $(id -u) != "0" ]
then
  echo 'Attempting to append sudo..'
  sudo "$0" "$@" 
  exit $?
fi

USER=$SUDO_USER
SITENAME=$1
WEBROOT="/var/www/vhosts"
DOMAIN=$2
MACRO_LIST='sites.conf'
DB_USER='root'
DB_PASS=$4
ALIASES=$3

echo $SITENAME

# Create the skeleton
echo "Creating directory skeleton"
mkdir $WEBROOT/$SITENAME
mkdir $WEBROOT/$SITENAME/docroot
mkdir $WEBROOT/$SITENAME/tmp
chown www-data $WEBROOT/$SITENAME/tmp
chown $USER:$USER $WEBROOT/$SITENAME -R

# Add an entry to apache
echo "Adding VHost to Apache"
echo "Use VHost $SITENAME $DOMAIN $ALIASES" >> /etc/apache2/sites-available/$MACRO_LIST
/etc/init.d/apache2 restart

# Create empty database. Need the wrapping backticks to allow database names with dashes
echo "Creating empty database with root credentials"
mysql -u $DB_USER -p$DB_PASS -e "create database \`$SITENAME\`;"

# todo: Add a user for this site


# Drush alias
echo "<?php
 \$sites['$SITENAME'] = array(
   'local_uri' => '$DOMAIN',
   'local_root' => '$WEBROOT/$SITENAME/docroot',
   'local_path' => '$WEBROOT/$SITENAME/docroot/sites/default',
   'remote_uri' => '',
   'remote_root' => '',
   'remote_path' => '',
   'remote_host' => '',
   'remote_user' => REMOTE_USER,
   'remote_dump' => '', 
  );?>
  " >> ~/.drush/aliases.inc

echo "Done."
